### ISSUE TITLE
Pretrained Model 

### ISSUE THREAD

**Issue by ccc870206** [qinglew/PCN-PyTorch#4]
Hi, it's very great work on the implementation of PCN in PyTorch!
I want to further study this work. Therefore, is it possible that you also provide your pretrained model? 
Many thanks.

**Comment by liuhuaijjin** [comment]
Expect the author to publish a pretraining model

**Comment by qinglew** [comment]
I published a pretrained model in directory `log/`, please check it! In fact, according to the visualization of completion result, the pretrained model is not good enough, and I only trianed with the category of car. When I trained the model, the batch size is very small because I have only a low level GPU 2060. Maybe you can train the model with bigger batch size.

**Comment by liuhuaijjin** [comment]
I am very glad that you can reply to me, the recent GRNet network effect may be a little better than PCN
